import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Frontend",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
        <div className="min-h-screen bg-neutral-400 text-white">
          <div className="application-border">
            <div className="left-info">
              <Sidebar />
            </div>
            <div className="right-info">
              <div className="information">
                {children}
              </div>
                
            </div>
          </div>
        </div>
        
      </body>
    </html>
  );
}
